### ISSUE TITLE
Получение ошибки 500 в Postman при отправке запроса на создание карточки жилья

### ISSUE THREAD

**Issue by SlyusNat** [RusinVladislav/skyrent#1]
1. Зайти в Postman
2. Создать HTTP-request
3. Выбрать метод POST
4. Использовать URL  https://vladislavrusin.pythonanywhere.com/places/
5. В тело запроса вставить JSON  
    {
        "description": "The building is shaped like an L. The extension extends into stylish gardens reaching until the end of that side of the house.",
        "country": "Spain",
        "features_off": "AC, Netflix, an iron, fireplace, bike",
        "picture_url": "https://images.unsplash.com/photo-1501877008226-4fca48ee50c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
        "city": "Madrid",
        "host_name": "{{$randomFirstName}}",
        "host_phone": "{{$randomPhoneNumber}}",
        "title": "{{$randomPhrase}}",
        "price": "450",
        "features_on": "Terrace, Fitness, Desk, Parking, WiFi",
        "host_location": "{{$randomStreetAddress}}"
    }
6. Нажать кнопку SEND

ОР: В теле ответа получаем "Place add"
ФР: Получаем ошибку сервера 500

**Comment by RusinVladislav** [comment]
Исправил
